### ISSUE TITLE
Problem adding file

### ISSUE THREAD

**Issue by mpjz** [muellert/on.video#1]
Environment: 
on.video 0.2.2
Plone 4.3.1
Python 2.7.3
(openSuse 12.3)

Installation of on.video with buildout went ok. Very simple initial test environment.
Apache listening on localhost (port 80), video files and metadata in /srv/www/htdocs (default document root). Accessing files (both video and metadata) via Apache works.

on.vido has been added as an extension to the test site in Plone.
File system path has been set to /srv/www/htdocs and BaseURL to 
http://localhost/ 

The "Add new" dropdown contains the new "Video" item. In the form to add an item, if I try to add a video the following error is thrown after submitting the page:

Traceback (innermost last):
  Module ZPublisher.Publish, line 126, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 46, in call_object
  Module plone.z3cform.layout, line 66, in **call**
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.add, line 112, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 141, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in **call**
  Module z3c.form.button, line 170, in **call**
  Module plone.dexterity.browser.add, line 95, in handleAdd
  Module z3c.form.group, line 95, in extractData
  Module z3c.form.form, line 146, in extractData
  Module z3c.form.field, line 311, in extract
  Module plone.directives.form.validator, line 17, in validate
  Module on.video.video, line 501, in validateFilename
TypeError: argument of type 'NoneType' is not iterable

Note: If I enter a non existing  metadata file e.g. blub, correctly the following error is shown 
" Basename of the video metadata file - eg. for 'myvideo.metadata', enter 'myvideo'.  
Video metadata file does not exist, or is inaccessible, at /srv/www/htdocs/blub.metadata"

As well if I use a metadata file with corrupt information (e.g. non existing filename) the correct error 

"Basename of the video metadata file - eg. for 'myvideo.metadata', enter 'myvideo'.  
Corrupt video metadata file at /srv/www/htdocs/Eurex_Group_The_Company_Film.metadata"

is shown, i.e. Plone has access to the configured location on the file system and reads the metadata file correctly.

The stackdump is thrown if I use (I assume) correct metadata. I also get the same result if I place the metadata/video files that are part of the on.video test suite in this location. 

Is this a bug or user error?

P.S. I note in config.py the line PLAYER = "flowplayer-3.2.5.swf". This is not exposed via the Plone extension configuration. Where does this file need to live in the installation?

**Comment by muellert** [comment]
Can you please send me the offending file? Looking at the code suggests that I missed something in verifying the metadata file, and I'd then add your metadata file to the test suite.

**Comment by muellert** [comment]
The flowplayer binary being hardcoded is a case of YANGI - I wanted to make that configurable, but so far, the requirement didn't really pop up. But feel free to adjust to your taste, eg. if you want to use a newer version.

**Comment by mpjz** [comment]
Hello,

no need to send a file. The problem is easily reproduced using the sample_video_1.metadata file that comes with the distribution.

Concerning the flowplayer binary, two questions: 

a.) It's easy to change config.py in the buildout-cache directory, but how do i trigger a recompilation? Re-running buildout does not do the trick.
b) Where do I need to copy the flowplayer executable? Same directory where the videos are stored, somewhere in the plone directory tree, somewhere else?

**Comment by muellert** [comment]
I have tried to fix the problem, but can't get the associated test to pass. Can you please give it a try?

**Comment by mpjz** [comment]
I see that the source on github has changed, how do I install this into my Plone site? Up to now I've only used buildout to install extensions. I am more than happy to read the fine manual if you just give me a pointer where it is ;-)

**Comment by muellert** [comment]
You have to copy the tree to the src directory. Follow the outline given here:

http://developer.plone.org/reference_manuals/active/helloworld/extend/addon.html

But instead of running zopeskel, you git clone the product from github.

Imho, you may need to add the product to the zcml section like this (try only if it fails to build otherwise):

zcml =
    on.video

Then run buildout and verify that the product is correctly imported and that you don't get the version from PyPI instead (delete that if necessary).

**Comment by mpjz** [comment]
Downloaded and installed the latest version from Github as instructed. It definitly is a step in the right direction. I can add a video element now, but still it is not displayed correctly on the page. I do see an empty flowplayer frame, but no video. I think the code responsible for this is 
        <video width="720" height="540" controls="control" poster="/++resource++on.video/novideo.png" tabindex="0">

```
        <!-- list the available video files for the player: -->
        <!-- specify the actual player: -->

            <object width="720" height="540" type="application/x-shockwave-flash" data="http://localhost/flowplayer-3.2.5.swf">
            <param name="movie" value="http://localhost/flowplayer-3.2.5.swf" />
            <param value="true" name="allowFullScreen">
            <param value="transparent" name="wmode">

            <param name="flashvars" value="config={'playlist':['/++resource++on.video/novideo.png',{'url':'video not available','autoPlay':false}]}" />
                <img src="/++resource++on.video/novideo.png" alt="Test" title="No video playback capabilities, please download the video below" />
        </object>
    </video>
```

I would expect the video file to appear somewhere in there. Loading the video in question direcly (via http://localhost/) works fine.

**Comment by muellert** [comment]
This code is being dynamically generated, depending on the contents of the metadata file and the presence of any listed video files on the file system, where the video files must be specified relative to the location of the metadata file. If the software determines that there is anything else wrong with the metadata file or the videos (or an exception occurs), a "no video" display like you posted, is being generated. Now it would be great to know the values you entered in the configlet, as well as the metadata file and a long directory listing of the relevant directory would be good to have.

**Comment by muellert** [comment]
Do you still experience the problem, or did you find a way to solve your problem?

**Comment by muellert** [comment]
Will close the bug in one or two weeks, unless there's further feedback.

**Comment by muellert** [comment]
No user reaction -> nothing more I can do?
